/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import ptraitements.TypeAbonnement;
import ptraitements.TypeCours;

/**
 *
 * @author rayan
 */
public class FAdminGestionClient extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdminGestionClient.class.getName());

    /**
     * Creates new form FAdminGestionClient
     */
    public FAdminGestionClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupeTypeCours = new javax.swing.ButtonGroup();
        JT_adresse_inscri = new javax.swing.JTextField();
        JL_nom_inscri = new javax.swing.JLabel();
        JL_ID_inscri = new javax.swing.JLabel();
        JT_NBplace = new javax.swing.JTextField();
        JL_prenom_inscri = new javax.swing.JLabel();
        jBenregistrer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JL_tel_inscri = new javax.swing.JLabel();
        JL_adresse_inscri = new javax.swing.JLabel();
        JT_Activite = new javax.swing.JTextField();
        JL_mdp_inscri = new javax.swing.JLabel();
        jRBindiv = new javax.swing.JRadioButton();
        jRBcoll = new javax.swing.JRadioButton();
        JtextJour = new javax.swing.JTextField();
        JtextMois = new javax.swing.JTextField();
        JtextAnnee = new javax.swing.JTextField();
        JtextHeure = new javax.swing.JTextField();
        JtextMinute = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JT_adresse_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_adresse_inscriActionPerformed(evt);
            }
        });

        JL_nom_inscri.setText("Heure");

        JL_ID_inscri.setText("Activité");

        JT_NBplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NBplaceActionPerformed(evt);
            }
        });

        JL_prenom_inscri.setText("Type Cours");

        jBenregistrer.setText("Enregistrer");
        jBenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenregistrerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 36)); // NOI18N
        jLabel1.setText("Modification info");

        JL_tel_inscri.setText("Nombre de place");

        JL_adresse_inscri.setText("Adresse");

        JT_Activite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_ActiviteActionPerformed(evt);
            }
        });

        JL_mdp_inscri.setText("Date");

        buttonGroupeTypeCours.add(jRBindiv);
        jRBindiv.setText("Individuel");
        jRBindiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBindivActionPerformed(evt);
            }
        });

        buttonGroupeTypeCours.add(jRBcoll);
        jRBcoll.setText("Collectif");

        JtextJour.setText("dd");
        JtextJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextJourActionPerformed(evt);
            }
        });

        JtextMois.setText("mm");
        JtextMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextMoisActionPerformed(evt);
            }
        });

        JtextAnnee.setText("aaaa");
        JtextAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextAnneeActionPerformed(evt);
            }
        });

        JtextHeure.setText("hh");
        JtextHeure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextHeureActionPerformed(evt);
            }
        });

        JtextMinute.setText("mm");
        JtextMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextMinuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_tel_inscri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JT_NBplace, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(JL_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(65, 65, 65)
                                                    .addComponent(JtextHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(JtextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(30, 30, 30))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(JL_ID_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(33, 33, 33)
                                                    .addComponent(JT_Activite, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JL_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(125, 125, 125))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JL_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRBcoll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRBindiv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(177, 177, 177)))
                                .addComponent(JL_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBenregistrer)
                                .addGap(208, 208, 208)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_tel_inscri)
                            .addComponent(JT_Activite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_NBplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_ID_inscri))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JL_mdp_inscri)
                                .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JL_adresse_inscri)
                                .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_nom_inscri)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtextHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(JL_prenom_inscri)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRBindiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBcoll)))
                .addGap(121, 121, 121)
                .addComponent(jBenregistrer)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_adresse_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_adresse_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_adresse_inscriActionPerformed

    private void JT_NBplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NBplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NBplaceActionPerformed

    class MoisInvalideException extends Exception {
    public MoisInvalideException(String message) {
        super(message);
    }
    }
    
    class JourInvalideException extends Exception {
    public JourInvalideException(String message) {
        super(message);
    }}
    
    
    private void jBenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenregistrerActionPerformed
        
        String activite = JT_Activite.getText();
        
        try {
            
        int j, m, a;
        j = Integer.parseInt(JtextJour.getText().trim());
        m = Integer.parseInt(JtextMois.getText().trim());
        a = Integer.parseInt(JtextAnnee.getText().trim());
        
        System.out.println("Jour: " + j + " Mois: " + m + " Annee: " + a);
        // Vérification du mois
        if (m <= 0) {
        throw new MoisInvalideException("Le mois doit être > 0");
        }
        if (m < 1 || m > 12) {
            throw new MoisInvalideException("Le mois doit être compris entre 1 et 12");
        }
        
        // Vérification du jours
        if (j<1 || j >30 ) {
            throw new JourInvalideException("Le jour doit être compris entre 1 et 30");
        }

        
        // 3. Création de la date
        // Note: LocalDate.of lancera sa propre exception si tu mets 31 juin par exemple
        LocalDate date = LocalDate.of(a, m, j);
        
        
        TypeCours type = null;
        
        
        // Selection du type d'abonnement
        if (jRBindiv.isSelected()) {
            type = TypeCours.Individuel;
            JT_NBplace.setText("1");
        } else if (jRBcoll.isSelected()) {
            type = TypeCours.Collectif;
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez choisir un type d'abonnement"); // inutile a present car saisie par defaut en place 
            return;
        }
        
        
        
    
    
            int h, n;
            h = Integer.parseInt(JtextHeure.getText().trim());
            n = Integer.parseInt(JtextMinute.getText().trim());
        
            System.out.println("Heure: " + j + " Minute: " + m);
            
            // Vérification du mois
            if (h < 0) {
            throw new MoisInvalideException("L'heure doit être > 0");
            }
            if (h < 0 || h > 23) {
                throw new MoisInvalideException("L'heure doit être compris entre 00 et 23");
            }
            if (n < 0) {
            throw new MoisInvalideException("La minute doit être > 0");
            }
            // Vérification du jours
            if (n<0 || n >59 ) {
                throw new JourInvalideException("La minute doit être compris entre 00 et 59");
            }
    
            LocalTime heure = LocalTime.of(h,n);
            
            
            int nbInscrit = Integer.parseInt(JT_NBplace.getText().trim());
            
        }
        catch (NumberFormatException ex) {
            String message = "Le format n'est pas bon !";
            JOptionPane.showMessageDialog(this, message); 
        }
        catch (MoisInvalideException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (JourInvalideException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (DateTimeException ex) {
        // Capture les erreurs comme le 31 février ou le 31 avril
        JOptionPane.showMessageDialog(this, "Cette date n'existe pas dans le calendrier.");
    }
        
        
    }//GEN-LAST:event_jBenregistrerActionPerformed

    private void JT_ActiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_ActiviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_ActiviteActionPerformed

    private void jRBindivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBindivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBindivActionPerformed

    private void JtextJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextJourActionPerformed

    private void JtextMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextMoisActionPerformed

    private void JtextAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextAnneeActionPerformed

    private void JtextHeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextHeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextHeureActionPerformed

    private void JtextMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextMinuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FAdminGestionClient dialog = new FAdminGestionClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_ID_inscri;
    private javax.swing.JLabel JL_adresse_inscri;
    private javax.swing.JLabel JL_mdp_inscri;
    private javax.swing.JLabel JL_nom_inscri;
    private javax.swing.JLabel JL_prenom_inscri;
    private javax.swing.JLabel JL_tel_inscri;
    private javax.swing.JTextField JT_Activite;
    private javax.swing.JTextField JT_NBplace;
    private javax.swing.JTextField JT_adresse_inscri;
    private javax.swing.JTextField JtextAnnee;
    private javax.swing.JTextField JtextHeure;
    private javax.swing.JTextField JtextJour;
    private javax.swing.JTextField JtextMinute;
    private javax.swing.JTextField JtextMois;
    private javax.swing.ButtonGroup buttonGroupeTypeCours;
    private javax.swing.JButton jBenregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBcoll;
    private javax.swing.JRadioButton jRBindiv;
    // End of variables declaration//GEN-END:variables
}
