/*
Vignes Gabriel
Ouchiha Rayane
Groupe CB
 */
package pfiches;

import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import ptraitements.Admin;
import ptraitements.Cours;
import ptraitements.Salle;
import ptraitements.TypeAbonnement;
import ptraitements.TypeCours;

/**
 * Fiche de modification d'un cours existant (admin uniquement).
 * Suit le même pattern que FAdminCreationCours :
 * - Les données du cours sélectionné sont pré-remplies à l'ouverture
 * - L'admin modifie ce qu'il veut et clique Enregistrer
 * - La modification est refusée si des clients sont déjà inscrits selon le nombre et si c'est une activité coll ou indiv (géré par Salle.modifierCours)
 * - La gestion des dates aurait pu être faite car théoriquement c'est possible mais pas primordiale
 * @author Vignes Gabriel / Ouchiha Rayane
 */
public class FAdminModifierCours extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdminModifierCours.class.getName());

        // ─── Attributs métier ────────────────────────────────────────────────────
        // Référence à la salle pour appeler modifierCours()
        private Salle maSalle;
    
        // L'admin connecté (utile pour la navigation retour)
        private Admin lAdmin;
    
        // Le cours que l'admin a sélectionné dans FAdminGestionCours
        // C'est cet objet qui sera modifié via maSalle.modifierCours()
        private Cours coursAModifier;
    
    
    /**
     * Creates new form FAdminGestionClient
     */
    public FAdminModifierCours(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); // centrage de la fenêtre
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupeTypeCours = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JtextMinute = new javax.swing.JTextField();
        JT_Activite = new javax.swing.JTextField();
        JL_mdp_inscri = new javax.swing.JLabel();
        JL_nom_inscri = new javax.swing.JLabel();
        JL_ID_inscri = new javax.swing.JLabel();
        JtextJour = new javax.swing.JTextField();
        JtextMois = new javax.swing.JTextField();
        JtextAnnee = new javax.swing.JTextField();
        JtextHeure = new javax.swing.JTextField();
        JL_tel_inscri = new javax.swing.JLabel();
        JT_NBplace = new javax.swing.JTextField();
        jBenregistrer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRBindiv = new javax.swing.JRadioButton();
        jRBcoll = new javax.swing.JRadioButton();
        JL_prenom_inscri = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 36)); // NOI18N
        jLabel1.setText("Modification de Cour : ");

        JtextMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextMinuteActionPerformed(evt);
            }
        });

        JT_Activite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_ActiviteActionPerformed(evt);
            }
        });

        JL_mdp_inscri.setText("Date : (dd/mm/aaaa)");

        JL_nom_inscri.setText("Heure : (hh : mm)");

        JL_ID_inscri.setText("Activité");

        JtextJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextJourActionPerformed(evt);
            }
        });

        JtextMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextMoisActionPerformed(evt);
            }
        });

        JtextAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextAnneeActionPerformed(evt);
            }
        });

        JtextHeure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextHeureActionPerformed(evt);
            }
        });

        JL_tel_inscri.setText("Nombre de place");

        JT_NBplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NBplaceActionPerformed(evt);
            }
        });

        jBenregistrer.setText("Enregistrer");
        jBenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenregistrerActionPerformed(evt);
            }
        });

        buttonGroupeTypeCours.add(jRBindiv);
        jRBindiv.setText("Individuel");
        jRBindiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBindivActionPerformed(evt);
            }
        });

        buttonGroupeTypeCours.add(jRBcoll);
        jRBcoll.setText("Collectif");
        jRBcoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBcollActionPerformed(evt);
            }
        });

        JL_prenom_inscri.setText("Type Cours");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBcoll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBindiv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JL_prenom_inscri)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRBindiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBcoll)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Liste Inscrits :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JL_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JL_ID_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(JT_Activite, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JL_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JT_NBplace, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(JtextHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JtextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBenregistrer)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JL_ID_inscri)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_mdp_inscri)
                            .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_tel_inscri)
                            .addComponent(JT_NBplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Activite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JtextHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JL_nom_inscri))
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jBenregistrer))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_NBplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NBplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NBplaceActionPerformed

    class MoisInvalideException extends Exception {
    public MoisInvalideException(String message) {
        super(message);
    }
    }
    
    class JourInvalideException extends Exception {
    public JourInvalideException(String message) {
        super(message);
    }}
    
    /**
        * Reçoit le cours à modifier depuis FAdminGestionCours et pré-remplit les champs.
        * Appelée AVANT setVisible(true).
        * 
        * Fait par Gabriel
    */
    public void envoyerDonneesVersModifCours(Salle maSalle, Admin admin, Cours cours) {
        this.maSalle = maSalle;
        this.lAdmin = admin;
        this.coursAModifier = cours;

        // Pré-remplissage des champs avec les valeurs actuelles du cours
        JT_Activite.setText(cours.getActivitecour());
        JtextJour.setText(String.valueOf(cours.getDatecour().getDayOfMonth()));
        JtextMois.setText(String.valueOf(cours.getDatecour().getMonthValue()));
        JtextAnnee.setText(String.valueOf(cours.getDatecour().getYear()));
        JtextHeure.setText(String.valueOf(cours.getHeurecour().getHour()));
        JtextMinute.setText(String.valueOf(cours.getHeurecour().getMinute()));
        JT_NBplace.setText(String.valueOf(cours.getNombrePlacescour()));

        // Pré-sélection du bon RadioButton
        if (cours.getTypeCours() == TypeCours.Individuel) {
            jRBindiv.setSelected(true);
            JT_NBplace.setEditable(false);
        } else {
             jRBcoll.setSelected(true);
            JT_NBplace.setEditable(true);
        }

        // Affichage de la liste des inscrits
        StringBuilder inscrits = new StringBuilder("<html><b>Inscrits (" + cours.getNbreInscrits() + ") :</b><br>");
        if (cours.getClientsInscritscours().isEmpty()) {
            inscrits.append("Aucun inscrit");
        } else {
            for (ptraitements.Client c : cours.getClientsInscritscours()) {
                inscrits.append("- ").append(c.getNom()).append(" ").append(c.getPrenom()).append("<br>");
            }
        }
        inscrits.append("</html>");
        jLabel2.setText(inscrits.toString());

        // Configuration des restrictions selon les inscrits — APRÈS le pré-remplissage
        configurerSelonInscrits();
}
    
    
    /**
        * Configure les composants selon le nombre d'inscrits au cours.
        * Appelée dans envoyerDonneesVersModifCours() après le pré-remplissage.
        * 
        * Logique réelle :
        * - Si 0 inscrit : tout est possible, aucune restriction
        * - Si 1 inscrit : on peut garder Individuel ou passer en Collectif, 
        *                  mais le nb de places minimum est 1
        * - Si 2+ inscrits : Individuel impossible (on le désactive),
        *                    le nb de places minimum = nb d'inscrits actuels
        * 
        * Fait par Gabriel
    */
    private void configurerSelonInscrits() {
        
        int nbInscrits = coursAModifier.getNbreInscrits();

        if (nbInscrits > 1) {
            // Impossible de passer en individuel : plusieurs clients sont inscrits
            // On désactive le bouton et on force Collectif
            jRBindiv.setEnabled(false);
            jRBcoll.setSelected(true);
            JT_NBplace.setEditable(true);

            // Message d'info dans le panel inscrits pour que l'admin comprenne pourquoi
            // (le label jLabel2 affiche déjà la liste, on enrichit juste le titre)
            jLabel2.setToolTipText("Individuel désactivé : " + nbInscrits + " clients inscrits.");

        } else if (nbInscrits == 1) {
            // 1 seul inscrit : on peut rester en individuel ou passer en collectif
            jRBindiv.setEnabled(true);

        } else {
            // 0 inscrit : toutes les options sont disponibles
            jRBindiv.setEnabled(true);
        }
    }
    
    
    /**
    * Bouton Enregistrer : valide les saisies et appelle maSalle.modifierCours().
    * 
    * Validations réelles ajoutées :
    * - On ne peut pas réduire les places en dessous du nb d'inscrits actuels
    * - Un cours individuel ne peut avoir qu'1 place
    * - Si 2+ inscrits, le passage en individuel est bloqué (déjà géré par les RadioButtons,
    *   mais on double-vérifie côté code au cas où)
    * 
    * Fait par Gabriel
    */
    
    private void jBenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenregistrerActionPerformed
        
        String activite = JT_Activite.getText().trim();
        int nbInscritsActuels = coursAModifier.getNbreInscrits();

        // Vérification que l'activité n'est pas vide
        if (activite.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le nom de l'activité ne peut pas être vide.");
        return;
        }

    try {
        // ── Validation de la date ──────────────────────────────────────────
        int j = Integer.parseInt(JtextJour.getText().trim());
        int m = Integer.parseInt(JtextMois.getText().trim());
        int a = Integer.parseInt(JtextAnnee.getText().trim());

        if (m < 1 || m > 12) throw new MoisInvalideException("Le mois doit être entre 1 et 12.");
        if (j < 1 || j > 31) throw new JourInvalideException("Le jour doit être entre 1 et 31.");

        LocalDate date = LocalDate.of(a, m, j); // lève DateTimeException si date impossible

        // Un cours passé ne peut pas être replanifié dans le futur non plus,
        // mais on laisse l'admin libre sur la date

        // ── Validation du type de cours ───────────────────────────────────
        TypeCours type;
        if (jRBindiv.isSelected()) {
            // Double vérification : normalement le bouton est désactivé si nbInscrits > 1
            if (nbInscritsActuels > 1) {
                JOptionPane.showMessageDialog(this,
                    "Impossible de passer en Individuel : " + nbInscritsActuels +
                    " clients sont inscrits.\nVeuillez les désinscrire d'abord.");
                return;
            }
            type = TypeCours.Individuel;
        } else if (jRBcoll.isSelected()) {
            type = TypeCours.Collectif;
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez choisir un type de cours.");
            return;
        }

        // ── Validation de l'heure ─────────────────────────────────────────
        int h = Integer.parseInt(JtextHeure.getText().trim());
        int n = Integer.parseInt(JtextMinute.getText().trim());

        if (h < 0 || h > 23) throw new MoisInvalideException("L'heure doit être entre 00 et 23.");
        if (n < 0 || n > 59) throw new JourInvalideException("La minute doit être entre 00 et 59.");

        LocalTime heure = LocalTime.of(h, n);

        // ── Validation du nombre de places ────────────────────────────────
        int nbPlace = Integer.parseInt(JT_NBplace.getText().trim());

        if (nbPlace < 1) {
            JOptionPane.showMessageDialog(this, "Le nombre de places doit être d'au moins 1.");
            return;
        }

        // Logique réelle : on ne peut pas avoir moins de places que d'inscrits actuels
        // (sinon des clients se retrouveraient dans un cours "plein" sans y être inscrits)
        if (nbPlace < nbInscritsActuels) {
            JOptionPane.showMessageDialog(this,
                "Impossible : " + nbInscritsActuels + " client(s) sont déjà inscrits.\n" +
                "Le nombre de places minimum est " + nbInscritsActuels + ".");
            return;
        }

        if (type == TypeCours.Individuel && nbPlace != 1) {
            JOptionPane.showMessageDialog(this, "Un cours Individuel ne peut avoir qu'1 place.");
            return;
        }

        // ── Appel de la modification via Salle ────────────────────────────
        // On passe outre la restriction de Salle.modifierCours() qui refuse
        // dès qu'il y a des inscrits, car ici on a nos propres validations plus fines.
        // On modifie donc directement les attributs du cours via les setters.
        coursAModifier.setActivite(activite);
        coursAModifier.setDate(date);
        coursAModifier.setHeure(heure);
        coursAModifier.setTypeCours(type);
        coursAModifier.setNombrePlaces(nbPlace);

        maSalle.sauvegarderTout();
        JOptionPane.showMessageDialog(this, "Cours modifié avec succès !");

        // Retour vers la gestion des cours, centré sur la semaine du cours modifié
        FAdminGestionCours fiche = ((FConnexionUti) getOwner()).getFicheAdminGestionCours();
        this.setVisible(false);
        fiche.setVisible(true);
        fiche.initialiserAffichage(date);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Un champ numérique contient une valeur invalide.");
    } catch (MoisInvalideException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    } catch (JourInvalideException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    } catch (DateTimeException ex) {
        JOptionPane.showMessageDialog(this, "Cette date n'existe pas dans le calendrier.");
    }
        
    }//GEN-LAST:event_jBenregistrerActionPerformed

    private void JT_ActiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_ActiviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_ActiviteActionPerformed

    
    /**
    * Sélection Individuel : force 1 place et bloque le champ.
    */

    private void jRBindivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBindivActionPerformed
        JT_NBplace.setText("1");
        JT_NBplace.setEditable(false); // on bloque pour éviter une valeur différente de 1
    }//GEN-LAST:event_jRBindivActionPerformed

    private void JtextJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextJourActionPerformed

    private void JtextMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextMoisActionPerformed

    private void JtextAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextAnneeActionPerformed

    private void JtextHeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextHeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextHeureActionPerformed

    private void JtextMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextMinuteActionPerformed

    
    
    /**
    * Sélection Collectif : débloque le champ.
    * On remet le nb de places actuel comme valeur minimale suggérée.
    */
    private void jRBcollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBcollActionPerformed
        JT_NBplace.setEditable(true);
        // Si on repasse en collectif depuis individuel, on remet la valeur d'origine
        if (coursAModifier != null && coursAModifier.getNbreInscrits() > 0) {
            JT_NBplace.setText(String.valueOf(coursAModifier.getNombrePlacescour()));
        } else {
            JT_NBplace.setText("");
        }
    }//GEN-LAST:event_jRBcollActionPerformed

    
    
    /**
    * Bouton Annuler : retour sans sauvegarder.
    * Fait par Gabriel
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        ((FConnexionUti) getOwner()).getFicheAdminGestionCours().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FAdminModifierCours dialog = new FAdminModifierCours(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_ID_inscri;
    private javax.swing.JLabel JL_mdp_inscri;
    private javax.swing.JLabel JL_nom_inscri;
    private javax.swing.JLabel JL_prenom_inscri;
    private javax.swing.JLabel JL_tel_inscri;
    private javax.swing.JTextField JT_Activite;
    private javax.swing.JTextField JT_NBplace;
    private javax.swing.JTextField JtextAnnee;
    private javax.swing.JTextField JtextHeure;
    private javax.swing.JTextField JtextJour;
    private javax.swing.JTextField JtextMinute;
    private javax.swing.JTextField JtextMois;
    private javax.swing.ButtonGroup buttonGroupeTypeCours;
    private javax.swing.JButton jBenregistrer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBcoll;
    private javax.swing.JRadioButton jRBindiv;
    // End of variables declaration//GEN-END:variables
}
