/*
Vignes Gabriel
Ouchiha Rayane
Groupe CB
 */
package pfiches;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import ptraitements.Admin;
import ptraitements.Client;
import ptraitements.Salle;

/**
 *
 * @author rayan
 */
public class FAdminGestionClientVraie extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdminGestionClientVraie.class.getName());
    private ArrayList<javax.swing.JCheckBox> listeCheckBox = new ArrayList<>();
    private ArrayList<javax.swing.JTextField> listeTextFields = new ArrayList<>();
    private ArrayList<String> listeTypes = new ArrayList<>();
    private Salle maSalle;

    /**
     * Creates new form FAdminGestionClientVraie
     */
    public FAdminGestionClientVraie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // ORDRE TRES IMPORTANT PR GARDER LE LIEN ENTRE CHACUN DES DEUX PAR LA SUITE 
        listeCheckBox.add(jCB_ID);
        listeTextFields.add(jTF_ID);
        listeTypes.add("numero");
        
        listeCheckBox.add(jCB_Tel);
        listeTextFields.add(jTF_Tel);
        listeTypes.add("telephone");
        
        listeCheckBox.add(jCB_Nom);
        listeTextFields.add(jTF_Nom);
        listeTypes.add("nom");
        
        listeCheckBox.add(jCB_Prenom);
        listeTextFields.add(jTF_Prenom);
        listeTypes.add("prenom");

        jTF_ID.setText("");
        jTF_Nom.setText("");
        jTF_Prenom.setText("");
        jTF_Tel.setText("");
        jTF_ID.setText("");
        
       this.maSalle = ((FConnexionUti)this.getOwner()).getsalle();
        /* Admin adminS = new  Admin("1","2");     
        maSalle = new Salle("Gabray_Sport",adminS,"Salledata");           POUR LES TES DE FENETRES 
        maSalle.chargerTout(); */  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab_Clients = new javax.swing.JTable();
        jPannel_2PanneldeToolbox = new javax.swing.JPanel();
        jB_MenuAdmin = new javax.swing.JButton();
        jBRetourVersConnex = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTF_ID = new javax.swing.JTextField();
        jTF_Tel = new javax.swing.JTextField();
        jCB_ID = new javax.swing.JCheckBox();
        jCB_Tel = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTF_Nom = new javax.swing.JTextField();
        jTF_Prenom = new javax.swing.JTextField();
        jCB_Nom = new javax.swing.JCheckBox();
        jCB_Prenom = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCB_Abonnement = new javax.swing.JCheckBox();
        JRB_Annuel = new javax.swing.JRadioButton();
        jRB_Trimestriel = new javax.swing.JRadioButton();
        jRB_Semestre = new javax.swing.JRadioButton();
        jRB_Inactif = new javax.swing.JRadioButton();
        jB_Rechercher = new javax.swing.JButton();
        jB_trier = new javax.swing.JButton();
        jB_ActivAbo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jB_Semestriel = new javax.swing.JButton();
        jB_Trimestriel = new javax.swing.JButton();
        jB_Annuel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Gestion des clients : ");

        jTab_Clients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTab_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tel", "Nom", "Prenom", "Abonnement", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTab_Clients.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTab_Clients);

        jPannel_2PanneldeToolbox.setBackground(new java.awt.Color(204, 204, 204));
        jPannel_2PanneldeToolbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jB_MenuAdmin.setBackground(new java.awt.Color(204, 255, 204));
        jB_MenuAdmin.setText("Menu");
        jB_MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MenuAdminActionPerformed(evt);
            }
        });

        jBRetourVersConnex.setBackground(new java.awt.Color(255, 102, 102));
        jBRetourVersConnex.setText("Retour");
        jBRetourVersConnex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBRetourVersConnex.setIconTextGap(5);
        jBRetourVersConnex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBRetourVersConnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetourVersConnexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPannel_2PanneldeToolboxLayout = new javax.swing.GroupLayout(jPannel_2PanneldeToolbox);
        jPannel_2PanneldeToolbox.setLayout(jPannel_2PanneldeToolboxLayout);
        jPannel_2PanneldeToolboxLayout.setHorizontalGroup(
            jPannel_2PanneldeToolboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannel_2PanneldeToolboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_MenuAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRetourVersConnex)
                .addContainerGap())
        );
        jPannel_2PanneldeToolboxLayout.setVerticalGroup(
            jPannel_2PanneldeToolboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBRetourVersConnex)
            .addComponent(jB_MenuAdmin)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCB_ID.setText("ID : ");
        jCB_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_IDActionPerformed(evt);
            }
        });

        jCB_Tel.setText("Tel : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_ID)
                    .addComponent(jCB_Tel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Tel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jCB_ID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Tel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTF_Nom.setText("jTextField3");
        jTF_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NomActionPerformed(evt);
            }
        });

        jTF_Prenom.setText("jTextField4");

        jCB_Nom.setText("Nom : ");

        jCB_Prenom.setText("Prenom :");
        jCB_Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_PrenomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Nom)
                    .addComponent(jCB_Prenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Prenom))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jCB_Abonnement.setText("Abonnement :");

        buttonGroup1.add(JRB_Annuel);
        JRB_Annuel.setText("Annuel");
        JRB_Annuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_AnnuelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRB_Trimestriel);
        jRB_Trimestriel.setText("Trimestriel");
        jRB_Trimestriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_TrimestrielActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRB_Semestre);
        jRB_Semestre.setText("Semestriel");

        buttonGroup1.add(jRB_Inactif);
        jRB_Inactif.setText("Inactif");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCB_Abonnement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRB_Annuel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRB_Trimestriel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRB_Semestre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRB_Inactif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_Abonnement)
                    .addComponent(JRB_Annuel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRB_Trimestriel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRB_Semestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRB_Inactif)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jB_Rechercher.setText("Rechercher");
        jB_Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RechercherActionPerformed(evt);
            }
        });

        jB_trier.setText("Trier");

        jB_ActivAbo.setText("Activer / Desactiver");
        jB_ActivAbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ActivAboActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jB_Semestriel.setText("Semestriel");
        jB_Semestriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SemestrielActionPerformed(evt);
            }
        });

        jB_Trimestriel.setText("Trimestriel");
        jB_Trimestriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_TrimestrielActionPerformed(evt);
            }
        });

        jB_Annuel.setText("Annuel");
        jB_Annuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AnnuelActionPerformed(evt);
            }
        });

        jLabel2.setText("Changer l'Abonnement");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jB_Trimestriel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Annuel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Semestriel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Trimestriel)
                    .addComponent(jB_Annuel)
                    .addComponent(jB_Semestriel))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPannel_2PanneldeToolbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jB_ActivAbo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jB_Rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jB_trier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPannel_2PanneldeToolbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jB_Rechercher)
                        .addGap(18, 18, 18)
                        .addComponent(jB_trier)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_ActivAbo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MenuAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_MenuAdminActionPerformed

    private void jBRetourVersConnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetourVersConnexActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ((FConnexionUti)this.getOwner()).getFicheAdminMenu().setVisible(true);
    }//GEN-LAST:event_jBRetourVersConnexActionPerformed

    private void jCB_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_IDActionPerformed

    private void jCB_PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_PrenomActionPerformed

    private void JRB_AnnuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_AnnuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_AnnuelActionPerformed

    private void jRB_TrimestrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_TrimestrielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_TrimestrielActionPerformed

    private void jTF_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NomActionPerformed

    private void jB_RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RechercherActionPerformed
        // TODO add your handling code here:
        // Verif que chaque champ est au bon format 
        ArrayList<Client> resultat = new ArrayList<>(maSalle.getListeClients()); // pr duppliquer la liste des clients
        
      
        // boucle de parcours : 
        for(int i=0; i < listeCheckBox.size(); i++){
            // Coché ou pas 
            if (listeCheckBox.get(i).isSelected()){
                String type = listeTypes.get(i); // on recupère  si c un nom un prenom un tel ou un id 
                String valeur = listeTextFields.get(i).getText().trim(); // on recupere ce qu'il y a des les Textes fields sans espaces
                
                // Est cque qlq choque est ecrite dans le TF
                if (!valeur.isBlank()){ resultat = maSalle.rechercherClientGeneral(type,valeur,resultat);}
                else{javax.swing.JOptionPane.showMessageDialog(this, "Aucun client trouvé avec ces critères.", "Recherche infructueuse", javax.swing.JOptionPane.INFORMATION_MESSAGE);}

            }
        }
                    // Gestion pr l'abonnelent 
            if(jCB_Abonnement.isSelected()){

                String aboVal = "";                
                if (JRB_Annuel.isSelected()) {
                    aboVal = "ANNUEL";
                } else if (jRB_Trimestriel.isSelected()) {
                     aboVal ="TRIMESTRIEL";
                } else if (jRB_Semestre.isSelected()) {
                     aboVal = "SEMESTRIEL";
                } else if (jRB_Inactif.isSelected()) {
                     aboVal = "INACTIF";
                }



                resultat = maSalle.rechercherClientGeneral("abonnement", aboVal, resultat);
            }
            
            // Affichage dans le tableau
            // Affichage dans le tableau
            if (resultat.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Aucun client trouvé.", 
                    "Recherche infructueuse", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                afficherDansTableau(resultat);
}
            

    }//GEN-LAST:event_jB_RechercherActionPerformed

    private void jB_ActivAboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ActivAboActionPerformed
        // TODO add your handling code here:
        if (getClientSelectionne() == null) {
        boolean nvEtat = !this.getClientSelectionne().isAbonnementActif();
        String ActiOuPas = "";
        if (nvEtat){ActiOuPas = " Activé ! ";}
        if (!nvEtat) {ActiOuPas = " Desactivé ! ";} 
        
        this.maSalle.setAbo(nvEtat,this.getClientSelectionne());
        maSalle.sauvegarderClients();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Abonnement de " + this.getClientSelectionne().getNom() + ActiOuPas);
        afficherDansTableau(maSalle.getListeClients()); // Rafraichir l'affichage
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this,"Selectionner Une ligne");
        }
    }//GEN-LAST:event_jB_ActivAboActionPerformed

    private void jB_TrimestrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_TrimestrielActionPerformed
        // TODO add your handling code here:
        this.maSalle.setAboTrime(this.getClientSelectionne());
        maSalle.sauvegarderClients();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Abonnement de " + this.getClientSelectionne().getNom() + " changé en TRIMESTRIEL.");
        afficherDansTableau(maSalle.getListeClients()); // Rafraichir l'affichage
    }//GEN-LAST:event_jB_TrimestrielActionPerformed

    private void jB_SemestrielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SemestrielActionPerformed
        // TODO add your handling code here:
        this.maSalle.setAboSemestre(this.getClientSelectionne());
        maSalle.sauvegarderClients();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Abonnement de " + this.getClientSelectionne().getNom() + " changé en SEMESTRIEL.");
        afficherDansTableau(maSalle.getListeClients()); // Rafraichir l'affichage
    }//GEN-LAST:event_jB_SemestrielActionPerformed

    private void jB_AnnuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AnnuelActionPerformed
        // TODO add your handling code here:
        this.maSalle.setAboAnnu(this.getClientSelectionne());
        maSalle.sauvegarderClients();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Abonnement de " + this.getClientSelectionne().getNom() + " changé en ANNUEL.");
        afficherDansTableau(maSalle.getListeClients()); // Rafraichir l'affichage
    }//GEN-LAST:event_jB_AnnuelActionPerformed
    
    // DECOUVERTE DE LA NOTION DE MODEL AVEC IA 
    // Affichage dans le tableau
    private void afficherDansTableau(ArrayList<Client> liste) {

        // 1. Récupérer le modèle du tableau
        DefaultTableModel modele = (DefaultTableModel) jTab_Clients.getModel();

        // 2. Vider le tableau avant d'afficher les nouveaux résultats
        modele.setRowCount(0);

        // 3. Parcourir la liste et ajouter chaque client ligne par ligne
        for (Client c : liste) {
            modele.addRow(new Object[]{
                c.getNumeroClient(),
                c.getTelephone(),
                c.getNom(),
                c.getPrenom(),
                c.getTypeAbonnement(), // ex: "ANNUEL", "INACTIF", etc.
                c.isAbonnementActif()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FAdminGestionClientVraie dialog = new FAdminGestionClientVraie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private Client getClientSelectionne() {
    int ligneSelectionnee = jTab_Clients.getSelectedRow();
    
    if (ligneSelectionnee == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner un client dans le tableau.",
            "Aucune sélection", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return null;
    }
    
    // Récupérer l'ID depuis la colonne 0 du tableau
    String idClient = jTab_Clients.getValueAt(ligneSelectionnee, 0).toString();
    
    // Retrouver le client dans maSalle par son ID
    for (Client c : maSalle.rechercherClient("numero", idClient)){ // BOUCLE INUTILE, CAR NUMERO UNIQUE MAIS FLEMME DE FAIRE AUTREMENT.
        if (c.getNumeroClient() == Integer.parseInt(idClient)){
            return c;    
        }
    }
    return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRB_Annuel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBRetourVersConnex;
    private javax.swing.JButton jB_ActivAbo;
    private javax.swing.JButton jB_Annuel;
    private javax.swing.JButton jB_MenuAdmin;
    private javax.swing.JButton jB_Rechercher;
    private javax.swing.JButton jB_Semestriel;
    private javax.swing.JButton jB_Trimestriel;
    private javax.swing.JButton jB_trier;
    private javax.swing.JCheckBox jCB_Abonnement;
    private javax.swing.JCheckBox jCB_ID;
    private javax.swing.JCheckBox jCB_Nom;
    private javax.swing.JCheckBox jCB_Prenom;
    private javax.swing.JCheckBox jCB_Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPannel_2PanneldeToolbox;
    private javax.swing.JRadioButton jRB_Inactif;
    private javax.swing.JRadioButton jRB_Semestre;
    private javax.swing.JRadioButton jRB_Trimestriel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_ID;
    private javax.swing.JTextField jTF_Nom;
    private javax.swing.JTextField jTF_Prenom;
    private javax.swing.JTextField jTF_Tel;
    private javax.swing.JTable jTab_Clients;
    // End of variables declaration//GEN-END:variables
}
