/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author rayan
 */
public class FAdminGestionCours extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FAdminGestionCours.class.getName());

    /**
     * Creates new form FAdminGestionCours
     */
    public FAdminGestionCours(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBCreerCours = new javax.swing.JButton();
        JL_ajout_photo = new javax.swing.JLabel();
        JT_nom_inscri = new javax.swing.JTextField();
        JT_prenom_inscri = new javax.swing.JTextField();
        JL_nom_inscri = new javax.swing.JLabel();
        JB_Ajout_Photo_inscri = new javax.swing.JButton();
        JL_prenom_inscri = new javax.swing.JLabel();
        JtextJour = new javax.swing.JTextField();
        JtextMois = new javax.swing.JTextField();
        JtextAnnee = new javax.swing.JTextField();
        jButonRechercher = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 36)); // NOI18N
        jLabel1.setText("Creer cours");

        jBCreerCours.setText("S'inscrire");
        jBCreerCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreerCoursActionPerformed(evt);
            }
        });

        JL_ajout_photo.setText("Ajouter Photo");

        JT_nom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_nom_inscriActionPerformed(evt);
            }
        });

        JT_prenom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_prenom_inscriActionPerformed(evt);
            }
        });

        JL_nom_inscri.setText("Nom");

        JB_Ajout_Photo_inscri.setText(". . .");
        JB_Ajout_Photo_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Ajout_Photo_inscriActionPerformed(evt);
            }
        });

        JL_prenom_inscri.setText("Prenom");

        JtextJour.setText("dd");
        JtextJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextJourActionPerformed(evt);
            }
        });

        JtextMois.setText("mm");
        JtextMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextMoisActionPerformed(evt);
            }
        });

        JtextAnnee.setText("aaaa");
        JtextAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextAnneeActionPerformed(evt);
            }
        });

        jButonRechercher.setText("Rechercher");
        jButonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonRechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBCreerCours)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JL_ajout_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JB_Ajout_Photo_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                                .addComponent(jButonRechercher)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtextJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtextMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtextAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButonRechercher))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_nom_inscri)
                    .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Ajout_Photo_inscri)
                    .addComponent(JL_ajout_photo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_prenom_inscri)
                    .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCreerCours)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_nom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_nom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_nom_inscriActionPerformed

    private void JT_prenom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_prenom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_prenom_inscriActionPerformed

    private void JB_Ajout_Photo_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Ajout_Photo_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_Ajout_Photo_inscriActionPerformed

    private void jBCreerCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreerCoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCreerCoursActionPerformed

    private void JtextJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextJourActionPerformed

    private void JtextMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextMoisActionPerformed

    private void JtextAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextAnneeActionPerformed

    
     class MoisInvalideException extends Exception {
    public MoisInvalideException(String message) {
        super(message);
    }
    }
    
    class JourInvalideException extends Exception {
    public JourInvalideException(String message) {
        super(message);
    }}
    
    
    
    private void jButonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonRechercherActionPerformed

        try {

            int j, m, a;
            j = Integer.parseInt(JtextJour.getText());
            m = Integer.parseInt(JtextMois.getText());
            a = Integer.parseInt(JtextAnnee.getText());

            // Vérification du mois
            if (m <= 0) {
                throw new MoisInvalideException("Le mois doit être > 0");
            }
            if (m % 12 != 0) {
                throw new MoisInvalideException("Le mois doit être compris entre 1 et 12");
            }

            // Vérification du jours
            if (j<0 || j >30 ) {
                throw new JourInvalideException("Le jour doit être compris entre 1 et 30");
            }
            else {
                if (j>28){
                    j = 28;
                }
            }

            
        }
        catch (NumberFormatException ex) {
            String message = "Le format n'est pas bon !";
            JOptionPane.showMessageDialog(this, message);
        }
        catch (MoisInvalideException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        catch (JourInvalideException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButonRechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FAdminGestionCours dialog = new FAdminGestionCours(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Ajout_Photo_inscri;
    private javax.swing.JLabel JL_ajout_photo;
    private javax.swing.JLabel JL_nom_inscri;
    private javax.swing.JLabel JL_prenom_inscri;
    private javax.swing.JTextField JT_nom_inscri;
    private javax.swing.JTextField JT_prenom_inscri;
    private javax.swing.JTextField JtextAnnee;
    private javax.swing.JTextField JtextJour;
    private javax.swing.JTextField JtextMois;
    private javax.swing.JButton jBCreerCours;
    private javax.swing.JToggleButton jButonRechercher;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
