/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import ptraitements.*;




/**
 *
 * @author gabri
 */
public class FClientMenu extends javax.swing.JDialog {
    
    
    private Salle maSalle;
    private Client Client;
    private FModifInfoClient fichModifInfoClient;
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FClientMenu.class.getName());

    /**
     * Creates new form PClient
     */
    public FClientMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fichModifInfoClient = new FModifInfoClient(parent, false); 
        
    }

    
    public void iniAffichage() {
    JL_PRE.setText(Client.getPrenom());
    JL_NomBjr.setText(Client.getNom());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_PRE = new javax.swing.JLabel();
        JB_histo = new javax.swing.JButton();
        JL_NomBjr = new javax.swing.JLabel();
        JB_Activite = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTB_InfosMenuC = new javax.swing.JToolBar();
        jB_MenuClient = new javax.swing.JButton();
        JB_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JL_PRE.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JL_PRE.setText("Bonjour,");

        JB_histo.setText("Historique");

        JL_NomBjr.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        JB_Activite.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        JB_Activite.setText("Activité");

        jTB_InfosMenuC.setRollover(true);

        jB_MenuClient.setText("jButton2");
        jTB_InfosMenuC.add(jB_MenuClient);

        JB_info.setText("Info");
        JB_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_infoActionPerformed(evt);
            }
        });
        jTB_InfosMenuC.add(JB_info);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTB_InfosMenuC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTB_InfosMenuC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(JB_histo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Activite, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JL_PRE)
                .addGap(18, 18, 18)
                .addComponent(JL_NomBjr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JL_PRE, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(JL_NomBjr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_histo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Activite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void envoyerSalleClientVersMenuClient(Salle maSalle, Client client){
        this.maSalle = maSalle;
        this.Client = client;
        iniAffichage();
    }
    
    


    
    
    private void JB_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_infoActionPerformed
       fichModifInfoClient.envoyerDonneesVersModifInfo(maSalle, Client);     
       
       this.setVisible(false);
       fichModifInfoClient.setVisible(true);

    }//GEN-LAST:event_JB_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FClientMenu dialog = new FClientMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Activite;
    private javax.swing.JButton JB_histo;
    private javax.swing.JButton JB_info;
    private javax.swing.JLabel JL_NomBjr;
    private javax.swing.JLabel JL_PRE;
    private javax.swing.JButton jB_MenuClient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jTB_InfosMenuC;
    // End of variables declaration//GEN-END:variables
}
