/*
Vignes Gabriel
Ouchiha Rayane
Groupe CB
 */
package pfiches;

import java.io.File;
import javax.swing.ImageIcon;
import ptraitements.*;
import ptraitements.Client;

/**
 *
 * @author rayan
 */
public class FConnexionUti extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FConnexionUti.class.getName());
    private Salle maSalle;
    private FActivite fichActivite;
    private FAdminMenu fichAdmin;
    private FClientMenu fichClient;
    private FHistoriqueCoursClient fichHistorique;
    private FInscrire fichInscrire;
    private FAdminCreationCours fichAdminCreationCours;
    private FAdminModifierCours fichFAdminModifierCours;
    private FAdminGestionClientVraie fichFAdminGestionClientVraie;
    private FAdminGestionCours fichAdminGestionCours;
    private FAdminStatsCours fichAdminStatsCours;
    private FModifInfoClient fichModifInfoClient;
    private FprofilClient fichprofilClient;
    
    protected String ad_id = "admin" ; protected  String ad_mdp = "admin123";
         
    /**
     * Creates new form FAcceuil
     */
    public FConnexionUti() {
        
        Admin adminS = new  Admin(ad_id,ad_mdp);     
        maSalle = new Salle("Gabray_Sport",adminS,"Salledata");
        maSalle.chargerTout();
          
        initComponents();
        Outilsgraphiques.AfficherImageBTaille(JL_logo, "logoSalle2Sport2.png");
        
        
        fichActivite = new FActivite(this, false);
        fichAdmin = new FAdminMenu(this, false);
        fichClient = new FClientMenu(this, false);
        fichHistorique = new FHistoriqueCoursClient(this, false);
        fichInscrire = new FInscrire(this, false);


        
        fichAdminGestionCours = new FAdminGestionCours(this, false);
        fichFAdminModifierCours = new FAdminModifierCours(this, false);
        fichFAdminGestionClientVraie = new FAdminGestionClientVraie(this, false);
        fichAdminCreationCours = new FAdminCreationCours(this, false);
        fichAdminStatsCours = new FAdminStatsCours(this, false);
        fichModifInfoClient = new FModifInfoClient(this, false);
        fichprofilClient = new FprofilClient(this, false);
        
        this.setLocationRelativeTo(null); // ON CENTRE LA FENETRE
        Outilsgraphiques.AfficherImageBTaille(JL_logo, "logoSalle2Sport2.png");  
    }

    public Salle getsalle(){
        return this.maSalle;
    }
    
    public FClientMenu getFicheClientMenu(){return this.fichClient;}
    public FprofilClient getFicheClientProfile(){return this.fichprofilClient;}
    public FModifInfoClient getFichClientModifInfo(){return this.fichModifInfoClient;}
    public FActivite getFicheActivite() { return this.fichActivite; }
    
    public FAdminGestionCours getFicheAdminGestionCours() { return this.fichAdminGestionCours; }
    public FAdminCreationCours getFicheAdminCreationCours() { return this.fichAdminCreationCours; }
    public FAdminMenu getFicheAdminMenu(){return this.fichAdmin;}
    public FAdminModifierCours getFicheAdminModifCours(){return this.fichFAdminModifierCours;}
    public FAdminStatsCours getFichAdminStats() {return this.fichAdminStatsCours;}
    public FAdminGestionClientVraie getFicheAdminGestionClient() {return this.fichFAdminGestionClientVraie;}
    
    
    public FHistoriqueCoursClient getFicheHistorique(){return this.fichHistorique;}

    
    public void clearChamps(){JF_ID.setText(""); JF_mdp.setText("");}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_logo = new javax.swing.JLabel();
        JB_inscrire = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JF_mdp = new javax.swing.JTextField();
        JF_ID = new javax.swing.JTextField();
        JL_ID = new javax.swing.JLabel();
        JL_mdp = new javax.swing.JLabel();
        JL_SeConnecter = new javax.swing.JLabel();
        JBconnection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        JB_inscrire.setText("S'inscrire");
        JB_inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_inscrireActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        // On crée une bordure arrondie grise
        jPanel1.setBorder(new com.formdev.flatlaf.ui.FlatLineBorder(
            new java.awt.Insets(10, 10, 10, 10), // Marges à l'intérieur du panel
            new java.awt.Color(150, 150, 150),   // Couleur de la ligne (Gris clair)
            1,                                   // Épaisseur du trait
            30                                   // L'ARRONDI
        ));

        JL_ID.setText("ID :");

        JL_mdp.setText("Mdp :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JL_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(JL_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JF_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_ID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_mdp))
                .addGap(17, 17, 17))
        );

        JL_SeConnecter.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JL_SeConnecter.setText("Connexion");

        JBconnection.setFont(new java.awt.Font("Gadugi", 3, 12)); // NOI18N
        JBconnection.setText("Se connecter");
        JBconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconnectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(JL_SeConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBconnection)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JL_SeConnecter)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBconnection)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JB_inscrire)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_inscrire)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconnectionActionPerformed
        // TODO add your handling code here:
        String mdp, id;
        Utilisateur user;
        
        mdp = JF_mdp.getText();
        id = JF_ID.getText();
        
        // Pas besoin au final, methode de classe déja optimale
      /*  boolean isAdmin = false;
        if ((id == null ? ad_id == null : id.equals(ad_id)) && (mdp == null ? ad_mdp == null : mdp.equals(ad_mdp))){ // equals avec verification de null proposée par netbeans
            isAdmin = true;
            user = maSalle.seConnecter(id, mdp);

        }
        
        if ( isAdmin = false){
            
            
        } */
      user = maSalle.seConnecter(id,mdp);
      
      if (user != null){
          if (user instanceof Admin) {
              Admin a = (Admin) user; // On transforme l'Utilisateur en Admin
            fichAdmin.setLocation(this.getLocation());
            this.setVisible(false);
            fichAdmin.setVisible(true);
            
            fichAdmin.envoyerSalleAdminVersMenuAdmin(maSalle, a); // Envoie des données
          }
          else if (user instanceof Client){
            Client c = (Client) user; // On transforme l'Utilisateur en Client
            this.setVisible(false);
            fichClient.setLocation(this.getLocation());
            fichClient.envoyerSalleClientVersMenuClient(maSalle, c); // Envoie des données
            fichClient.setVisible(true);
            
          }
      }
        
        
    }//GEN-LAST:event_JBconnectionActionPerformed

    private void JB_inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_inscrireActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichInscrire.setVisible(true);
    }//GEN-LAST:event_JB_inscrireActionPerformed

    public void chargerImagesFCo() {
   Outilsgraphiques.AfficherImageBTaille(JL_logo, "logoSalle2Sport2.png");
     /*File f = new File("images/logoSalle2Sport2.png");
    System.out.println("Image trouvée : " + f.exists());
    System.out.println("Chemin absolu : " + f.getAbsolutePath());
    // TEST TAILLE DU LABEL A L APPEL 
    System.out.println("Largeur label : " + JL_logo.getWidth());
    System.out.println("Hauteur label : " + JL_logo.getHeight());
    // AUTRE TEST
    ImageIcon icon = new ImageIcon("C:/Users/rayan/Desktop/Algo A2/S4/Projet_salle2Sport_Graphique/Salle_2_sport_graphique/src/pimages/logoSalle2Sport2.png");
    System.out.println("Largeur icone : " + icon.getIconWidth());
    System.out.println("Hauteur icone : " + icon.getIconHeight());
    JL_logo.setIcon(icon);
    // Autre test 
    ImageIcon icon2 = new ImageIcon("C:/Users/rayan/Desktop/Algo A2/S4/Projet_salle2Sport_Graphique/Salle_2_sport_graphique/src/pimages/default-avatar.png");
    System.out.println("Largeur : " + icon2.getIconWidth());*/

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
//_______________________________________PARTIE RECHERCHEE SUR REDDIT________________________________
        try {
        // Cette ligne magique active le look moderne et sombre
        com.formdev.flatlaf.FlatLightLaf.setup();
        
        // On définit l'arrondi global (en pixels)
    javax.swing.UIManager.put( "Component.arc", 20 ); 
    javax.swing.UIManager.put( "Button.arc", 20 );

    } catch( Exception ex ) {
        System.err.println( "Échec de l'initialisation du thème" );
    }
//_______________________________________________________________________________________________________ 

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        FConnexionUti fenetre = new FConnexionUti();
        fenetre.setVisible(true);
        fenetre.chargerImagesFCo(); 
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_inscrire;
    private javax.swing.JButton JBconnection;
    private javax.swing.JTextField JF_ID;
    private javax.swing.JTextField JF_mdp;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_SeConnecter;
    private javax.swing.JLabel JL_logo;
    private javax.swing.JLabel JL_mdp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
