/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfiches;

import ptraitements.*;

/**
 *
 * @author rayan
 */
public class FConnexionUti extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FConnexionUti.class.getName());
    private Salle maSalle;
    private FActivite fichActivite;
    private FAdminMenu fichAdmin;
    private FClientMenu fichClient;
    private FHistoriqueCoursClient fichHistorique;
    private FInscrire fichInscrire;
    private FAdminCreationCours fichAdminCreationCours;
    private FAdminGestionClient fichFAdminGestionClient;
    private FAdminGestionCours fichAdminGestionCours;
    private FAdminStatsCours fichAdminStatsCours;
    private FModifInfoClient fichModifInfoClient;
    private FprofilClient fichprofilClient;
    
    protected String ad_id = "admin" ; protected  String ad_mdp = "admin123";
         
    /**
     * Creates new form FAcceuil
     */
    public FConnexionUti() {
        initComponents();
        fichActivite = new FActivite(this, false);
        fichAdmin = new FAdminMenu(this, false);
        fichClient = new FClientMenu(this, false);
        fichHistorique = new FHistoriqueCoursClient(this, false);
        fichInscrire = new FInscrire(this, false);
        

        
        fichAdminCreationCours = new FAdminCreationCours(this, false);
        fichFAdminGestionClient = new FAdminGestionClient(this, false);
        fichAdminGestionCours = new FAdminGestionCours(this, false);
        fichAdminCreationCours.setVisible(true);
        fichAdminStatsCours = new FAdminStatsCours(this, false);
        fichModifInfoClient = new FModifInfoClient(this, false);
        fichprofilClient = new FprofilClient(this, false);
        
        Admin adminS = new  Admin(ad_id,ad_mdp);     
        maSalle = new Salle("Gabray_Sport",adminS,"Salledata");
        maSalle.chargerTout();

    }

    public Salle getsalle(){
        return this.maSalle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBconnection = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JF_mdp = new javax.swing.JTextField();
        JF_ID = new javax.swing.JTextField();
        JL_ID = new javax.swing.JLabel();
        JL_mdp = new javax.swing.JLabel();
        JL_SeConnecter = new javax.swing.JLabel();
        JL_logo = new javax.swing.JLabel();
        JB_inscrire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        JBconnection.setBackground(new java.awt.Color(255, 204, 204));
        JBconnection.setFont(new java.awt.Font("Gadugi", 3, 12)); // NOI18N
        JBconnection.setText("Se connecter");
        JBconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconnectionActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JL_ID.setText("ID :");

        JL_mdp.setText("Mdp :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JL_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(JL_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JF_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_ID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_mdp))
                .addGap(17, 17, 17))
        );

        JL_SeConnecter.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        JL_SeConnecter.setText("Connection");

        JL_logo.setText("LOGO");

        JB_inscrire.setText("S'inscrire");
        JB_inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_inscrireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JL_SeConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(JL_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JB_inscrire)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JL_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(JL_SeConnecter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(JB_inscrire)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconnectionActionPerformed
        // TODO add your handling code here:
        String mdp, id;
        Utilisateur user;
        
        mdp = JF_mdp.getText();
        id = JF_ID.getText();
        
        // Pas besoin au final, methode de classe déja optimale
      /*  boolean isAdmin = false;
        if ((id == null ? ad_id == null : id.equals(ad_id)) && (mdp == null ? ad_mdp == null : mdp.equals(ad_mdp))){ // equals avec verification de null proposée par netbeans
            isAdmin = true;
            user = maSalle.seConnecter(id, mdp);

        }
        
        if ( isAdmin = false){
            
            
        } */
      user = maSalle.seConnecter(id,mdp);
      
      if (user != null){
          if (user instanceof Admin){
            fichAdmin.setLocation(this.getLocation());
            this.setVisible(false);
            fichAdmin.setVisible(true);
          }
          else if (user instanceof Client){
          this.setVisible(false);
          fichClient.setVisible(true);
          }
      }
        
        
    }//GEN-LAST:event_JBconnectionActionPerformed

    private void JB_inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_inscrireActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichInscrire.setVisible(true);
    }//GEN-LAST:event_JB_inscrireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FConnexionUti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_inscrire;
    private javax.swing.JButton JBconnection;
    private javax.swing.JTextField JF_ID;
    private javax.swing.JTextField JF_mdp;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_SeConnecter;
    private javax.swing.JLabel JL_logo;
    private javax.swing.JLabel JL_mdp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
