/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.awt.FileDialog;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;
import ptraitements.TypeAbonnement;
import ptraitements.Client;

/**
 *
 * @author gabri
 */
public class FInscrire extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FInscrire.class.getName());

    /**
     * Creates new form FInscrire
     */
    public FInscrire(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jRadioButtonAnnuel.setSelected(true);    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAbonnement = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanelChampsAremplir = new javax.swing.JPanel();
        JT_Id_inscri = new javax.swing.JTextField();
        JT_nom_inscri = new javax.swing.JTextField();
        JT_mdp_inscri = new javax.swing.JTextField();
        JT_prenom_inscri = new javax.swing.JTextField();
        JL_ID_inscri = new javax.swing.JLabel();
        JL_mdp_inscri = new javax.swing.JLabel();
        JL_nom_inscri = new javax.swing.JLabel();
        JL_prenom_inscri = new javax.swing.JLabel();
        JL_adresse_inscri = new javax.swing.JLabel();
        JT_tel_inscri = new javax.swing.JTextField();
        JT_adresse_inscri = new javax.swing.JTextField();
        JL_tel_inscri = new javax.swing.JLabel();
        jRadioButtonTri = new javax.swing.JRadioButton();
        jRadioButtonSem = new javax.swing.JRadioButton();
        jBinscrire = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonAnnuel = new javax.swing.JRadioButton();
        JL_ajout_photo = new javax.swing.JLabel();
        JB_Ajout_Photo_inscri = new javax.swing.JButton();
        jLPhotoNom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        jPanelChampsAremplir.setBackground(new java.awt.Color(255, 204, 204));
        jPanelChampsAremplir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelChampsAremplir.setForeground(new java.awt.Color(255, 204, 204));

        JT_Id_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_Id_inscriActionPerformed(evt);
            }
        });

        JT_nom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_nom_inscriActionPerformed(evt);
            }
        });

        JT_mdp_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_mdp_inscriActionPerformed(evt);
            }
        });

        JT_prenom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_prenom_inscriActionPerformed(evt);
            }
        });

        JL_ID_inscri.setText("Identifiant");

        JL_mdp_inscri.setText("Mot de Passe ");

        JL_nom_inscri.setText("Nom");

        JL_prenom_inscri.setText("Prenom");

        JL_adresse_inscri.setText("Adresse");

        JT_tel_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_tel_inscriActionPerformed(evt);
            }
        });

        JT_adresse_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_adresse_inscriActionPerformed(evt);
            }
        });

        JL_tel_inscri.setText("Tel");

        buttonGroupAbonnement.add(jRadioButtonTri);
        jRadioButtonTri.setText("Trimestriel");

        buttonGroupAbonnement.add(jRadioButtonSem);
        jRadioButtonSem.setText("Hebdomadaire");
        jRadioButtonSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSemActionPerformed(evt);
            }
        });

        jBinscrire.setText("S'inscrire");
        jBinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscrireActionPerformed(evt);
            }
        });

        jLabel2.setText("Type abonnement ");

        buttonGroupAbonnement.add(jRadioButtonAnnuel);
        jRadioButtonAnnuel.setText("Annuel");
        jRadioButtonAnnuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnnuelActionPerformed(evt);
            }
        });

        JL_ajout_photo.setText("Ajouter Photo");

        JB_Ajout_Photo_inscri.setText("...");
        JB_Ajout_Photo_inscri.setAlignmentX(0.5F);
        JB_Ajout_Photo_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Ajout_Photo_inscriActionPerformed(evt);
            }
        });

        jLPhotoNom.setText("Pas de photo selectionné");

        javax.swing.GroupLayout jPanelChampsAremplirLayout = new javax.swing.GroupLayout(jPanelChampsAremplir);
        jPanelChampsAremplir.setLayout(jPanelChampsAremplirLayout);
        jPanelChampsAremplirLayout.setHorizontalGroup(
            jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addComponent(JL_ID_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addComponent(JL_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addComponent(JL_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JL_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JT_Id_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JT_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(78, 78, 78)
                .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChampsAremplirLayout.createSequentialGroup()
                        .addComponent(JL_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JT_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonSem)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChampsAremplirLayout.createSequentialGroup()
                                    .addComponent(jRadioButtonTri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addComponent(JL_ajout_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_Ajout_Photo_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jBinscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChampsAremplirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLPhotoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelChampsAremplirLayout.setVerticalGroup(
            jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_Id_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_ID_inscri))
                        .addGap(41, 41, 41)
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JL_mdp_inscri)
                            .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JT_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JL_adresse_inscri))))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_tel_inscri)
                            .addComponent(JT_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_nom_inscri)
                            .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_prenom_inscri)
                            .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2))
                    .addGroup(jPanelChampsAremplirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAnnuel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChampsAremplirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_ajout_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Ajout_Photo_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLPhotoNom)
                .addGap(2, 2, 2)
                .addComponent(jBinscrire)
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel1.setText("Inscription");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelChampsAremplir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChampsAremplir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_Id_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_Id_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_Id_inscriActionPerformed

    private void JT_nom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_nom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_nom_inscriActionPerformed

    private void JT_mdp_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_mdp_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_mdp_inscriActionPerformed

    private void JT_prenom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_prenom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_prenom_inscriActionPerformed

    private void JT_tel_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_tel_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_tel_inscriActionPerformed

    private void JT_adresse_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_adresse_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_adresse_inscriActionPerformed


    
    
    private void jBinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscrireActionPerformed
        

        String identifiant = JT_Id_inscri.getText();
        String motDePasse = JT_mdp_inscri.getText();
        String nom = JT_nom_inscri.getText();
        String prenom = JT_prenom_inscri.getText();
        String telephone = JT_tel_inscri.getText();
        String adresse = JT_adresse_inscri.getText();
        String pp = jLPhotoNom.getText();
        TypeAbonnement type = null;
        
        
    // Selection du type d'abonnement
    if (jRadioButtonAnnuel.isSelected()) {
        type = TypeAbonnement.ANNUEL;
    } else if (jRadioButtonTri.isSelected()) {
        type = TypeAbonnement.TRIMESTRIEL;
    } else if (jRadioButtonSem.isSelected()) {
        type = TypeAbonnement.SEMAINE;
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez choisir un type d'abonnement"); // inutile a present car saisie par defaut en place 
        return;
    }
    
    // vérification si une photo est sélectionné
    if ( jLPhotoNom.getText().equals("Pas de photo selectionné")){
        pp = "";
    } else {
        pp = jLPhotoNom.getText();
    }
    
    
    
    //Creation du client
    Client c = ((FConnexionUti) getOwner()).getsalle().creerCompte(
        identifiant, motDePasse, nom, prenom, telephone, adresse, type, pp
    );

    if (c == null) {
        JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé !");
    } else {
        // Sauvegarde + retour à la connexion                          // sauvegarde vrmt necessaire ? peut etre une autre methode qui va append le nv client au lieu de tt reecrire 
        ((FConnexionUti) getOwner()).getsalle().sauvegarderClients(); // Sauveguarde clients au lieu de tout, moins de ressources gaspillée 
        JOptionPane.showMessageDialog(this, "Compte créé avec succès !");
        getOwner().setVisible(true);
        this.dispose(); // dispose() permet de fermer la fenetre comme setVisible(false) mais la détruit de la mémoire car inutile ensuite, trouver avec IA
        
    }

        
        
        
        
    }//GEN-LAST:event_jBinscrireActionPerformed

    private void jRadioButtonAnnuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnnuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAnnuelActionPerformed

    private void jRadioButtonSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSemActionPerformed

    private void JB_Ajout_Photo_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Ajout_Photo_inscriActionPerformed
    //methode trouvé par ia mais assemblé par gabriel
    // Créer une instance de la classe FileDialog
    FileDialog dial = new FileDialog(this, "Sélectionner le fichier du dossier images", FileDialog.LOAD);
    
    // Rendre visible la fenêtre de dialogue
    dial.setVisible(true);
    
    // Récupérer le nom et le répertoire du fichier sélectionné
    String nomFich = dial.getFile();
    String repertoire = dial.getDirectory();
    jLPhotoNom.setText(nomFich);
    
    if (nomFich != null) {
    try {
        // On nettoie le nom : on remplace espaces et caractères spéciaux
        String nomNettoye = nomFich.replaceAll("[^a-zA-Z0-9._-]", "_");
        System.out.println("Nom nettoyé : " + nomNettoye); // DEBUG
        
        Path src = Paths.get(repertoire + nomFich);
        Path dest1 = Paths.get("src/pimages/" + nomNettoye);
        Path dest2 = Paths.get("target/classes/pimages/" + nomNettoye);

        // DEBUG - affiche où on copie vraiment
        System.out.println("Copie vers : " + dest2.toAbsolutePath());

        Files.copy(src, dest1, StandardCopyOption.REPLACE_EXISTING);
        Files.copy(src, dest2, StandardCopyOption.REPLACE_EXISTING);
        // On sauvegarde le NOM NETTOYÉ dans le label
        jLPhotoNom.setText(nomNettoye);
        
        JOptionPane.showMessageDialog(this, "Fichier ajouté avec succès !");
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }
    }//GEN-LAST:event_JB_Ajout_Photo_inscriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FInscrire dialog = new FInscrire(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Ajout_Photo_inscri;
    private javax.swing.JLabel JL_ID_inscri;
    private javax.swing.JLabel JL_adresse_inscri;
    private javax.swing.JLabel JL_ajout_photo;
    private javax.swing.JLabel JL_mdp_inscri;
    private javax.swing.JLabel JL_nom_inscri;
    private javax.swing.JLabel JL_prenom_inscri;
    private javax.swing.JLabel JL_tel_inscri;
    private javax.swing.JTextField JT_Id_inscri;
    private javax.swing.JTextField JT_adresse_inscri;
    private javax.swing.JTextField JT_mdp_inscri;
    private javax.swing.JTextField JT_nom_inscri;
    private javax.swing.JTextField JT_prenom_inscri;
    private javax.swing.JTextField JT_tel_inscri;
    private javax.swing.ButtonGroup buttonGroupAbonnement;
    private javax.swing.JButton jBinscrire;
    private javax.swing.JLabel jLPhotoNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelChampsAremplir;
    private javax.swing.JRadioButton jRadioButtonAnnuel;
    private javax.swing.JRadioButton jRadioButtonSem;
    private javax.swing.JRadioButton jRadioButtonTri;
    // End of variables declaration//GEN-END:variables
}
