/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import javax.swing.JOptionPane;
import ptraitements.Client;
import ptraitements.Salle;

/**
 *
 * @author rayan
 */
public class FModifInfoClient extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FModifInfoClient.class.getName());

    private Salle maSalle;
    private Client Client;
    private FClientMenu menuClient;
    
    /**
     * Creates new form FModifInfoClient
     */
    public FModifInfoClient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_mdp_inscri = new javax.swing.JLabel();
        JT_adresse_inscri = new javax.swing.JTextField();
        JL_nom_inscri = new javax.swing.JLabel();
        JB_Ajout_Photo_inscri = new javax.swing.JButton();
        JL_prenom_inscri = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JL_tel_inscri = new javax.swing.JLabel();
        JL_adresse_inscri = new javax.swing.JLabel();
        JL_ajout_photo = new javax.swing.JLabel();
        JT_Id_inscri = new javax.swing.JTextField();
        JT_nom_inscri = new javax.swing.JTextField();
        JT_mdp_inscri = new javax.swing.JTextField();
        JT_prenom_inscri = new javax.swing.JTextField();
        JL_ID_inscri = new javax.swing.JLabel();
        JT_tel_inscri = new javax.swing.JTextField();
        jBenregistrer = new javax.swing.JButton();
        JL_mdp = new javax.swing.JLabel();
        JL_nom = new javax.swing.JLabel();
        JL_ID = new javax.swing.JLabel();
        JL_prenom = new javax.swing.JLabel();
        JL_adresse = new javax.swing.JLabel();
        JL_tel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JL_mdp_inscri.setText("Mot de Passe ");

        JT_adresse_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_adresse_inscriActionPerformed(evt);
            }
        });

        JL_nom_inscri.setText("Nom");

        JB_Ajout_Photo_inscri.setText(". . .");
        JB_Ajout_Photo_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Ajout_Photo_inscriActionPerformed(evt);
            }
        });

        JL_prenom_inscri.setText("Prenom");

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 36)); // NOI18N
        jLabel1.setText("Modification info");

        JL_tel_inscri.setText("Tel");

        JL_adresse_inscri.setText("Adresse");

        JL_ajout_photo.setText("Ajouter Photo");

        JT_Id_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_Id_inscriActionPerformed(evt);
            }
        });

        JT_nom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_nom_inscriActionPerformed(evt);
            }
        });

        JT_mdp_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_mdp_inscriActionPerformed(evt);
            }
        });

        JT_prenom_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_prenom_inscriActionPerformed(evt);
            }
        });

        JL_ID_inscri.setText("Identifiant");

        JT_tel_inscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_tel_inscriActionPerformed(evt);
            }
        });

        jBenregistrer.setText("Enregistrer");
        jBenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenregistrerActionPerformed(evt);
            }
        });

        JL_mdp.setText("Mot de Passe ");

        JL_nom.setText("Nom");

        JL_ID.setText("Identifiant");

        JL_prenom.setText("Prenom");

        JL_adresse.setText("Adresse");

        JL_tel.setText("Tel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_ID_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_Id_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(JL_ajout_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Ajout_Photo_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_tel_inscri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBenregistrer)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_tel_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_ID_inscri))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JB_Ajout_Photo_inscri)
                                    .addComponent(JL_ajout_photo))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JT_adresse_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(JL_nom_inscri)
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_mdp_inscri)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(JL_prenom_inscri))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL_ID)
                                .addGap(95, 95, 95)
                                .addComponent(JL_nom))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_mdp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(JL_prenom))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JT_Id_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JL_tel_inscri)
                                    .addComponent(JL_tel))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JT_mdp_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JL_adresse_inscri)
                                    .addComponent(JL_adresse))
                                .addGap(29, 29, 29)
                                .addComponent(JT_nom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(JT_prenom_inscri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jBenregistrer)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_adresse_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_adresse_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_adresse_inscriActionPerformed

    private void JT_Id_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_Id_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_Id_inscriActionPerformed

    private void JT_nom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_nom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_nom_inscriActionPerformed

    private void JT_mdp_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_mdp_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_mdp_inscriActionPerformed

    private void JT_prenom_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_prenom_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_prenom_inscriActionPerformed

    private void JT_tel_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_tel_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_tel_inscriActionPerformed

    // fait par gabriel
    //envoie les donnees entre la fiche client, la modif d'info et la salle
    public void envoyerDonneesVersModifInfo(Salle salle, Client client, FClientMenu menu) {
    this.maSalle = salle;
    this.Client = client;
    this.menuClient = menu;
    
    JL_ID.setText(client.getIdentifiant());
    JL_mdp.setText(client.getMot2Passe());
    JL_nom.setText(client.getNom());
    JL_prenom.setText(client.getPrenom());
    JL_tel.setText(client.getTelephone());
    JL_adresse.setText(client.getAdresse());
     }

    
    
    private void jBenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenregistrerActionPerformed
       
       String NVidentifiant = JT_Id_inscri.getText();
       String NVmotDePasse = JT_mdp_inscri.getText();
       String NVnom = JT_nom_inscri.getText();
       String NVprenom  = JT_prenom_inscri.getText();
       String NVtelephone = JT_tel_inscri.getText();
       String NVadresse = JT_adresse_inscri.getText();
       String message = "Vous avez modifié :\n";
       boolean aucunChangement = true;
       
       //supprimer les infos précédement modifiés
       JT_Id_inscri.setText("");
       JT_mdp_inscri.setText("");
       JT_nom_inscri.setText("");
       JT_prenom_inscri.setText("");
       JT_tel_inscri.setText("");
       JT_adresse_inscri.setText("");



        // Des if séparés pour pouvoir modifier plusieurs champs à la fois
        // On vérifie si il a quelque chose avec isEmpty()
        if (!NVmotDePasse.isEmpty()) {
            Client.setMot2passe(NVmotDePasse);
            message += "- votre mot de passe\n";
            aucunChangement = false;
        }
        if (!NVnom.isEmpty()) {
            Client.modifNom(NVnom);
            message += "- votre Nom\n";
            aucunChangement = false;
        }
        if (!NVprenom.isEmpty()) {
            Client.modifPrenom(NVprenom);
            message += "- votre Prénom\n";
            aucunChangement = false;
        }
        if (!NVtelephone.isEmpty()) {
            Client.modifTelephone(NVtelephone);
            message += "- votre Téléphone\n";
            aucunChangement = false;
        }
        if (!NVadresse.isEmpty()) {
            Client.modifAdresse(NVadresse);
            message += "- votre Adresse\n";
            aucunChangement = false;
        }

        if (aucunChangement) {
            message = "Vous n'avez rien changé.";
        }
    
        // Sauvegarde
        maSalle.sauvegarderTout();

        JOptionPane.showMessageDialog(this, message);
        this.setVisible(false);
        menuClient.setVisible(true);                            
        menuClient.iniAffichage();
    }//GEN-LAST:event_jBenregistrerActionPerformed

    private void JB_Ajout_Photo_inscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Ajout_Photo_inscriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_Ajout_Photo_inscriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FModifInfoClient dialog = new FModifInfoClient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Ajout_Photo_inscri;
    private javax.swing.JLabel JL_ID;
    private javax.swing.JLabel JL_ID_inscri;
    private javax.swing.JLabel JL_adresse;
    private javax.swing.JLabel JL_adresse_inscri;
    private javax.swing.JLabel JL_ajout_photo;
    private javax.swing.JLabel JL_mdp;
    private javax.swing.JLabel JL_mdp_inscri;
    private javax.swing.JLabel JL_nom;
    private javax.swing.JLabel JL_nom_inscri;
    private javax.swing.JLabel JL_prenom;
    private javax.swing.JLabel JL_prenom_inscri;
    private javax.swing.JLabel JL_tel;
    private javax.swing.JLabel JL_tel_inscri;
    private javax.swing.JTextField JT_Id_inscri;
    private javax.swing.JTextField JT_adresse_inscri;
    private javax.swing.JTextField JT_mdp_inscri;
    private javax.swing.JTextField JT_nom_inscri;
    private javax.swing.JTextField JT_prenom_inscri;
    private javax.swing.JTextField JT_tel_inscri;
    private javax.swing.JButton jBenregistrer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
